version: '3.7'

services:
  postgres:
    image: postgres:16.3
    container_name: smartwardrobe.postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - smartwardrobe-network

  smartwardrobe.api:
    build:
      dockerfile: D:\Курсова\SmartWardrobe\API\Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
      BUILD_CONFIGURATION: Development
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - smartwardrobe-network
    command: ["dotnet", "API.dll"]

networks:
  smartwardrobe-network:
    driver: bridge
